chain = "somm"
channel = "channel-0"
denom = "usomm"
prefix = "somm"
gas_per_byte = 10
base_gas = 110000
ibc_memo = "This should not cause any problems"
memo = "Just checking on this"
ibc_memo_repeat = 10
rand_min = 300000
rand_max = 400000
revision_number = 4
timeout_height = 20720608

[gas]
zero = 0
low = 0.1
medium = 0.25
high = 0.04


[nodes]
rpc  = [
"http://135.181.210.171:2077",
]


api = "https://sommelier-api.polkachu.com:443"



