chain = "Sei"
channel = "channel-1"
denom = "usei"
prefix = "sei"
gas_per_byte = 10
base_gas = 110000
ibc_memo = "This should not cause any problems"
memo = "Just checking on this"
ibc_memo_repeat = 10
rand_min = 300000
rand_max = 400000
revision_number = 4
timeout_height = 20720608

[gas]
zero = 0.02
low = 0.02
medium = 0.02
high = 0.04


[nodes]
rpc  = [
    "https://sei-rpc.lavenderfive.com:443",
    "https://sei-rpc.polkachu.com",
    "https://sei-rpc.brocha.in",
    "https://rpc-sei.stingray.plus",
    "https://rpc-sei.whispernode.com:443",
    "https://sei.rpc.kjnodes.com",
    "https://sei-rpc.publicnode.com:443",

]

api = "https://sei-api.polkachu.com:443"



